// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/ocx_handshake.proto

package ocxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 1. HELLO: Initiator introduces themselves
type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InitiatorId   string                 `protobuf:"bytes,1,opt,name=initiator_id,json=initiatorId,proto3" json:"initiator_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"` // e.g., "1.0.0"
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_proto_ocx_handshake_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ocx_handshake_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_proto_ocx_handshake_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetInitiatorId() string {
	if x != nil {
		return x.InitiatorId
	}
	return ""
}

func (x *HelloRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HelloRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type HelloResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SessionId         string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status            string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "HELLO_ACK"
	SupportedVersions string                 `protobuf:"bytes,3,opt,name=supported_versions,json=supportedVersions,proto3" json:"supported_versions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_proto_ocx_handshake_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ocx_handshake_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_proto_ocx_handshake_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HelloResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HelloResponse) GetSupportedVersions() string {
	if x != nil {
		return x.SupportedVersions
	}
	return ""
}

// 2. CHALLENGE: Responder sends a crypto puzzle
type ChallengeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeRequest) Reset() {
	*x = ChallengeRequest{}
	mi := &file_proto_ocx_handshake_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeRequest) ProtoMessage() {}

func (x *ChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ocx_handshake_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeRequest.ProtoReflect.Descriptor instead.
func (*ChallengeRequest) Descriptor() ([]byte, []int) {
	return file_proto_ocx_handshake_proto_rawDescGZIP(), []int{2}
}

func (x *ChallengeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ChallengeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         string                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`            // Random string to be signed
	Difficulty    int32                  `protobuf:"varint,2,opt,name=difficulty,proto3" json:"difficulty,omitempty"` // For PoW if needed (optional)
	Algorithm     string                 `protobuf:"bytes,3,opt,name=algorithm,proto3" json:"algorithm,omitempty"`    // "SHA256-RSA"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeResponse) Reset() {
	*x = ChallengeResponse{}
	mi := &file_proto_ocx_handshake_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeResponse) ProtoMessage() {}

func (x *ChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ocx_handshake_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeResponse.ProtoReflect.Descriptor instead.
func (*ChallengeResponse) Descriptor() ([]byte, []int) {
	return file_proto_ocx_handshake_proto_rawDescGZIP(), []int{3}
}

func (x *ChallengeResponse) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *ChallengeResponse) GetDifficulty() int32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *ChallengeResponse) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

// 3. PROOF: Initiator solves/signs the challenge
type ProofRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SignedNonce   string                 `protobuf:"bytes,2,opt,name=signed_nonce,json=signedNonce,proto3" json:"signed_nonce,omitempty"` // Signature of the nonce
	PublicKey     string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`       // To verify signature
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProofRequest) Reset() {
	*x = ProofRequest{}
	mi := &file_proto_ocx_handshake_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProofRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProofRequest) ProtoMessage() {}

func (x *ProofRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ocx_handshake_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProofRequest.ProtoReflect.Descriptor instead.
func (*ProofRequest) Descriptor() ([]byte, []int) {
	return file_proto_ocx_handshake_proto_rawDescGZIP(), []int{4}
}

func (x *ProofRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ProofRequest) GetSignedNonce() string {
	if x != nil {
		return x.SignedNonce
	}
	return ""
}

func (x *ProofRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type ProofResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "PROOF_ACCEPTED" or "PROOF_REJECTED"
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProofResponse) Reset() {
	*x = ProofResponse{}
	mi := &file_proto_ocx_handshake_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProofResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProofResponse) ProtoMessage() {}

func (x *ProofResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ocx_handshake_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProofResponse.ProtoReflect.Descriptor instead.
func (*ProofResponse) Descriptor() ([]byte, []int) {
	return file_proto_ocx_handshake_proto_rawDescGZIP(), []int{5}
}

func (x *ProofResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProofResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 4. VERIFY: Responder validates identity against Registry
type VerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_proto_ocx_handshake_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ocx_handshake_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_proto_ocx_handshake_proto_rawDescGZIP(), []int{6}
}

func (x *VerifyRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type VerifyResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IsVerified     bool                   `protobuf:"varint,1,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	RegistryStatus string                 `protobuf:"bytes,2,opt,name=registry_status,json=registryStatus,proto3" json:"registry_status,omitempty"` // "ACTIVE", "SUSPENDED"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_proto_ocx_handshake_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ocx_handshake_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_proto_ocx_handshake_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyResponse) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *VerifyResponse) GetRegistryStatus() string {
	if x != nil {
		return x.RegistryStatus
	}
	return ""
}

// 5. ATTESTATION: Exchange of Claims / Capabilities
type AttestationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Claims        map[string]string      `protobuf:"bytes,2,rep,name=claims,proto3" json:"claims,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // e.g. "role": "auditor", "clearance": "L3"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttestationRequest) Reset() {
	*x = AttestationRequest{}
	mi := &file_proto_ocx_handshake_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestationRequest) ProtoMessage() {}

func (x *AttestationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ocx_handshake_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestationRequest.ProtoReflect.Descriptor instead.
func (*AttestationRequest) Descriptor() ([]byte, []int) {
	return file_proto_ocx_handshake_proto_rawDescGZIP(), []int{8}
}

func (x *AttestationRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AttestationRequest) GetClaims() map[string]string {
	if x != nil {
		return x.Claims
	}
	return nil
}

type AttestationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "CLAIMS_RECEIVED"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttestationResponse) Reset() {
	*x = AttestationResponse{}
	mi := &file_proto_ocx_handshake_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestationResponse) ProtoMessage() {}

func (x *AttestationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ocx_handshake_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestationResponse.ProtoReflect.Descriptor instead.
func (*AttestationResponse) Descriptor() ([]byte, []int) {
	return file_proto_ocx_handshake_proto_rawDescGZIP(), []int{9}
}

func (x *AttestationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 6. FINALIZE (DECISION): Final Accept/Reject
type FinalizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeRequest) Reset() {
	*x = FinalizeRequest{}
	mi := &file_proto_ocx_handshake_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeRequest) ProtoMessage() {}

func (x *FinalizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ocx_handshake_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeRequest.ProtoReflect.Descriptor instead.
func (*FinalizeRequest) Descriptor() ([]byte, []int) {
	return file_proto_ocx_handshake_proto_rawDescGZIP(), []int{10}
}

func (x *FinalizeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type FinalizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decision      string                 `protobuf:"bytes,1,opt,name=decision,proto3" json:"decision,omitempty"`                             // "ACCEPTED" or "REJECTED"
	SessionToken  string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"` // Bearer token for future requests
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeResponse) Reset() {
	*x = FinalizeResponse{}
	mi := &file_proto_ocx_handshake_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeResponse) ProtoMessage() {}

func (x *FinalizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ocx_handshake_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeResponse.ProtoReflect.Descriptor instead.
func (*FinalizeResponse) Descriptor() ([]byte, []int) {
	return file_proto_ocx_handshake_proto_rawDescGZIP(), []int{11}
}

func (x *FinalizeResponse) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *FinalizeResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *FinalizeResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

var File_proto_ocx_handshake_proto protoreflect.FileDescriptor

const file_proto_ocx_handshake_proto_rawDesc = "" +
	"\n" +
	"\x19proto/ocx_handshake.proto\x12\x06ocx.v1\"h\n" +
	"\fHelloRequest\x12!\n" +
	"\finitiator_id\x18\x01 \x01(\tR\vinitiatorId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\"u\n" +
	"\rHelloResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12-\n" +
	"\x12supported_versions\x18\x03 \x01(\tR\x11supportedVersions\"1\n" +
	"\x10ChallengeRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"g\n" +
	"\x11ChallengeResponse\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonce\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x02 \x01(\x05R\n" +
	"difficulty\x12\x1c\n" +
	"\talgorithm\x18\x03 \x01(\tR\talgorithm\"o\n" +
	"\fProofRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\fsigned_nonce\x18\x02 \x01(\tR\vsignedNonce\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\"?\n" +
	"\rProofResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\".\n" +
	"\rVerifyRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"Z\n" +
	"\x0eVerifyResponse\x12\x1f\n" +
	"\vis_verified\x18\x01 \x01(\bR\n" +
	"isVerified\x12'\n" +
	"\x0fregistry_status\x18\x02 \x01(\tR\x0eregistryStatus\"\xae\x01\n" +
	"\x12AttestationRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12>\n" +
	"\x06claims\x18\x02 \x03(\v2&.ocx.v1.AttestationRequest.ClaimsEntryR\x06claims\x1a9\n" +
	"\vClaimsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"-\n" +
	"\x13AttestationResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"0\n" +
	"\x0fFinalizeRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"r\n" +
	"\x10FinalizeResponse\x12\x1a\n" +
	"\bdecision\x18\x01 \x01(\tR\bdecision\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt2\xfb\x02\n" +
	"\x10HandshakeService\x124\n" +
	"\x05Hello\x12\x14.ocx.v1.HelloRequest\x1a\x15.ocx.v1.HelloResponse\x12@\n" +
	"\tChallenge\x12\x18.ocx.v1.ChallengeRequest\x1a\x19.ocx.v1.ChallengeResponse\x124\n" +
	"\x05Proof\x12\x14.ocx.v1.ProofRequest\x1a\x15.ocx.v1.ProofResponse\x127\n" +
	"\x06Verify\x12\x15.ocx.v1.VerifyRequest\x1a\x16.ocx.v1.VerifyResponse\x12A\n" +
	"\x06Attest\x12\x1a.ocx.v1.AttestationRequest\x1a\x1b.ocx.v1.AttestationResponse\x12=\n" +
	"\bFinalize\x12\x17.ocx.v1.FinalizeRequest\x1a\x18.ocx.v1.FinalizeResponseB+Z)github.com/ocx/backend/gen/proto/v1;ocxv1b\x06proto3"

var (
	file_proto_ocx_handshake_proto_rawDescOnce sync.Once
	file_proto_ocx_handshake_proto_rawDescData []byte
)

func file_proto_ocx_handshake_proto_rawDescGZIP() []byte {
	file_proto_ocx_handshake_proto_rawDescOnce.Do(func() {
		file_proto_ocx_handshake_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ocx_handshake_proto_rawDesc), len(file_proto_ocx_handshake_proto_rawDesc)))
	})
	return file_proto_ocx_handshake_proto_rawDescData
}

var file_proto_ocx_handshake_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_ocx_handshake_proto_goTypes = []any{
	(*HelloRequest)(nil),        // 0: ocx.v1.HelloRequest
	(*HelloResponse)(nil),       // 1: ocx.v1.HelloResponse
	(*ChallengeRequest)(nil),    // 2: ocx.v1.ChallengeRequest
	(*ChallengeResponse)(nil),   // 3: ocx.v1.ChallengeResponse
	(*ProofRequest)(nil),        // 4: ocx.v1.ProofRequest
	(*ProofResponse)(nil),       // 5: ocx.v1.ProofResponse
	(*VerifyRequest)(nil),       // 6: ocx.v1.VerifyRequest
	(*VerifyResponse)(nil),      // 7: ocx.v1.VerifyResponse
	(*AttestationRequest)(nil),  // 8: ocx.v1.AttestationRequest
	(*AttestationResponse)(nil), // 9: ocx.v1.AttestationResponse
	(*FinalizeRequest)(nil),     // 10: ocx.v1.FinalizeRequest
	(*FinalizeResponse)(nil),    // 11: ocx.v1.FinalizeResponse
	nil,                         // 12: ocx.v1.AttestationRequest.ClaimsEntry
}
var file_proto_ocx_handshake_proto_depIdxs = []int32{
	12, // 0: ocx.v1.AttestationRequest.claims:type_name -> ocx.v1.AttestationRequest.ClaimsEntry
	0,  // 1: ocx.v1.HandshakeService.Hello:input_type -> ocx.v1.HelloRequest
	2,  // 2: ocx.v1.HandshakeService.Challenge:input_type -> ocx.v1.ChallengeRequest
	4,  // 3: ocx.v1.HandshakeService.Proof:input_type -> ocx.v1.ProofRequest
	6,  // 4: ocx.v1.HandshakeService.Verify:input_type -> ocx.v1.VerifyRequest
	8,  // 5: ocx.v1.HandshakeService.Attest:input_type -> ocx.v1.AttestationRequest
	10, // 6: ocx.v1.HandshakeService.Finalize:input_type -> ocx.v1.FinalizeRequest
	1,  // 7: ocx.v1.HandshakeService.Hello:output_type -> ocx.v1.HelloResponse
	3,  // 8: ocx.v1.HandshakeService.Challenge:output_type -> ocx.v1.ChallengeResponse
	5,  // 9: ocx.v1.HandshakeService.Proof:output_type -> ocx.v1.ProofResponse
	7,  // 10: ocx.v1.HandshakeService.Verify:output_type -> ocx.v1.VerifyResponse
	9,  // 11: ocx.v1.HandshakeService.Attest:output_type -> ocx.v1.AttestationResponse
	11, // 12: ocx.v1.HandshakeService.Finalize:output_type -> ocx.v1.FinalizeResponse
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_ocx_handshake_proto_init() }
func file_proto_ocx_handshake_proto_init() {
	if File_proto_ocx_handshake_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ocx_handshake_proto_rawDesc), len(file_proto_ocx_handshake_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ocx_handshake_proto_goTypes,
		DependencyIndexes: file_proto_ocx_handshake_proto_depIdxs,
		MessageInfos:      file_proto_ocx_handshake_proto_msgTypes,
	}.Build()
	File_proto_ocx_handshake_proto = out.File
	file_proto_ocx_handshake_proto_goTypes = nil
	file_proto_ocx_handshake_proto_depIdxs = nil
}
