// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: proto/ocx_handshake.proto

package ocxv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HandshakeService_Hello_FullMethodName     = "/ocx.v1.HandshakeService/Hello"
	HandshakeService_Challenge_FullMethodName = "/ocx.v1.HandshakeService/Challenge"
	HandshakeService_Proof_FullMethodName     = "/ocx.v1.HandshakeService/Proof"
	HandshakeService_Verify_FullMethodName    = "/ocx.v1.HandshakeService/Verify"
	HandshakeService_Attest_FullMethodName    = "/ocx.v1.HandshakeService/Attest"
	HandshakeService_Finalize_FullMethodName  = "/ocx.v1.HandshakeService/Finalize"
)

// HandshakeServiceClient is the client API for HandshakeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HandshakeService defines the 6-step security protocol
type HandshakeServiceClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	Challenge(ctx context.Context, in *ChallengeRequest, opts ...grpc.CallOption) (*ChallengeResponse, error)
	Proof(ctx context.Context, in *ProofRequest, opts ...grpc.CallOption) (*ProofResponse, error)
	Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
	Attest(ctx context.Context, in *AttestationRequest, opts ...grpc.CallOption) (*AttestationResponse, error)
	Finalize(ctx context.Context, in *FinalizeRequest, opts ...grpc.CallOption) (*FinalizeResponse, error)
}

type handshakeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHandshakeServiceClient(cc grpc.ClientConnInterface) HandshakeServiceClient {
	return &handshakeServiceClient{cc}
}

func (c *handshakeServiceClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, HandshakeService_Hello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handshakeServiceClient) Challenge(ctx context.Context, in *ChallengeRequest, opts ...grpc.CallOption) (*ChallengeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChallengeResponse)
	err := c.cc.Invoke(ctx, HandshakeService_Challenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handshakeServiceClient) Proof(ctx context.Context, in *ProofRequest, opts ...grpc.CallOption) (*ProofResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProofResponse)
	err := c.cc.Invoke(ctx, HandshakeService_Proof_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handshakeServiceClient) Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyResponse)
	err := c.cc.Invoke(ctx, HandshakeService_Verify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handshakeServiceClient) Attest(ctx context.Context, in *AttestationRequest, opts ...grpc.CallOption) (*AttestationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttestationResponse)
	err := c.cc.Invoke(ctx, HandshakeService_Attest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handshakeServiceClient) Finalize(ctx context.Context, in *FinalizeRequest, opts ...grpc.CallOption) (*FinalizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinalizeResponse)
	err := c.cc.Invoke(ctx, HandshakeService_Finalize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HandshakeServiceServer is the server API for HandshakeService service.
// All implementations must embed UnimplementedHandshakeServiceServer
// for forward compatibility.
//
// HandshakeService defines the 6-step security protocol
type HandshakeServiceServer interface {
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
	Challenge(context.Context, *ChallengeRequest) (*ChallengeResponse, error)
	Proof(context.Context, *ProofRequest) (*ProofResponse, error)
	Verify(context.Context, *VerifyRequest) (*VerifyResponse, error)
	Attest(context.Context, *AttestationRequest) (*AttestationResponse, error)
	Finalize(context.Context, *FinalizeRequest) (*FinalizeResponse, error)
	mustEmbedUnimplementedHandshakeServiceServer()
}

// UnimplementedHandshakeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHandshakeServiceServer struct{}

func (UnimplementedHandshakeServiceServer) Hello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedHandshakeServiceServer) Challenge(context.Context, *ChallengeRequest) (*ChallengeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Challenge not implemented")
}
func (UnimplementedHandshakeServiceServer) Proof(context.Context, *ProofRequest) (*ProofResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Proof not implemented")
}
func (UnimplementedHandshakeServiceServer) Verify(context.Context, *VerifyRequest) (*VerifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedHandshakeServiceServer) Attest(context.Context, *AttestationRequest) (*AttestationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Attest not implemented")
}
func (UnimplementedHandshakeServiceServer) Finalize(context.Context, *FinalizeRequest) (*FinalizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Finalize not implemented")
}
func (UnimplementedHandshakeServiceServer) mustEmbedUnimplementedHandshakeServiceServer() {}
func (UnimplementedHandshakeServiceServer) testEmbeddedByValue()                          {}

// UnsafeHandshakeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HandshakeServiceServer will
// result in compilation errors.
type UnsafeHandshakeServiceServer interface {
	mustEmbedUnimplementedHandshakeServiceServer()
}

func RegisterHandshakeServiceServer(s grpc.ServiceRegistrar, srv HandshakeServiceServer) {
	// If the following call panics, it indicates UnimplementedHandshakeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HandshakeService_ServiceDesc, srv)
}

func _HandshakeService_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandshakeServiceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HandshakeService_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandshakeServiceServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HandshakeService_Challenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandshakeServiceServer).Challenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HandshakeService_Challenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandshakeServiceServer).Challenge(ctx, req.(*ChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HandshakeService_Proof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandshakeServiceServer).Proof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HandshakeService_Proof_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandshakeServiceServer).Proof(ctx, req.(*ProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HandshakeService_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandshakeServiceServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HandshakeService_Verify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandshakeServiceServer).Verify(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HandshakeService_Attest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttestationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandshakeServiceServer).Attest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HandshakeService_Attest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandshakeServiceServer).Attest(ctx, req.(*AttestationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HandshakeService_Finalize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandshakeServiceServer).Finalize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HandshakeService_Finalize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandshakeServiceServer).Finalize(ctx, req.(*FinalizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HandshakeService_ServiceDesc is the grpc.ServiceDesc for HandshakeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HandshakeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ocx.v1.HandshakeService",
	HandlerType: (*HandshakeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _HandshakeService_Hello_Handler,
		},
		{
			MethodName: "Challenge",
			Handler:    _HandshakeService_Challenge_Handler,
		},
		{
			MethodName: "Proof",
			Handler:    _HandshakeService_Proof_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _HandshakeService_Verify_Handler,
		},
		{
			MethodName: "Attest",
			Handler:    _HandshakeService_Attest_Handler,
		},
		{
			MethodName: "Finalize",
			Handler:    _HandshakeService_Finalize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ocx_handshake.proto",
}
