// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: proto/traffic_assessment.proto

package ocxv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrafficAssessor_InspectTraffic_FullMethodName = "/ocx.v1.TrafficAssessor/InspectTraffic"
)

// TrafficAssessorClient is the client API for TrafficAssessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The core service for real-time traffic assessment.
type TrafficAssessorClient interface {
	// Bidirectional stream allows the Interceptor to send packets
	// and receive verdicts asynchronously without closing the connection.
	InspectTraffic(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AssessmentRequest, AssessmentResponse], error)
}

type trafficAssessorClient struct {
	cc grpc.ClientConnInterface
}

func NewTrafficAssessorClient(cc grpc.ClientConnInterface) TrafficAssessorClient {
	return &trafficAssessorClient{cc}
}

func (c *trafficAssessorClient) InspectTraffic(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AssessmentRequest, AssessmentResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TrafficAssessor_ServiceDesc.Streams[0], TrafficAssessor_InspectTraffic_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AssessmentRequest, AssessmentResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrafficAssessor_InspectTrafficClient = grpc.BidiStreamingClient[AssessmentRequest, AssessmentResponse]

// TrafficAssessorServer is the server API for TrafficAssessor service.
// All implementations must embed UnimplementedTrafficAssessorServer
// for forward compatibility.
//
// The core service for real-time traffic assessment.
type TrafficAssessorServer interface {
	// Bidirectional stream allows the Interceptor to send packets
	// and receive verdicts asynchronously without closing the connection.
	InspectTraffic(grpc.BidiStreamingServer[AssessmentRequest, AssessmentResponse]) error
	mustEmbedUnimplementedTrafficAssessorServer()
}

// UnimplementedTrafficAssessorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrafficAssessorServer struct{}

func (UnimplementedTrafficAssessorServer) InspectTraffic(grpc.BidiStreamingServer[AssessmentRequest, AssessmentResponse]) error {
	return status.Error(codes.Unimplemented, "method InspectTraffic not implemented")
}
func (UnimplementedTrafficAssessorServer) mustEmbedUnimplementedTrafficAssessorServer() {}
func (UnimplementedTrafficAssessorServer) testEmbeddedByValue()                         {}

// UnsafeTrafficAssessorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrafficAssessorServer will
// result in compilation errors.
type UnsafeTrafficAssessorServer interface {
	mustEmbedUnimplementedTrafficAssessorServer()
}

func RegisterTrafficAssessorServer(s grpc.ServiceRegistrar, srv TrafficAssessorServer) {
	// If the following call panics, it indicates UnimplementedTrafficAssessorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrafficAssessor_ServiceDesc, srv)
}

func _TrafficAssessor_InspectTraffic_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TrafficAssessorServer).InspectTraffic(&grpc.GenericServerStream[AssessmentRequest, AssessmentResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrafficAssessor_InspectTrafficServer = grpc.BidiStreamingServer[AssessmentRequest, AssessmentResponse]

// TrafficAssessor_ServiceDesc is the grpc.ServiceDesc for TrafficAssessor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrafficAssessor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ocx.v1.TrafficAssessor",
	HandlerType: (*TrafficAssessorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InspectTraffic",
			Handler:       _TrafficAssessor_InspectTraffic_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/traffic_assessment.proto",
}
