// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/traffic_assessment.proto

package ocxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtocolType int32

const (
	ProtocolType_PROTOCOL_TYPE_UNSPECIFIED ProtocolType = 0
	ProtocolType_PROTOCOL_TYPE_TCP         ProtocolType = 1
	ProtocolType_PROTOCOL_TYPE_HTTP        ProtocolType = 2
	ProtocolType_PROTOCOL_TYPE_TLS         ProtocolType = 3
	ProtocolType_PROTOCOL_TYPE_DNS         ProtocolType = 4
)

// Enum value maps for ProtocolType.
var (
	ProtocolType_name = map[int32]string{
		0: "PROTOCOL_TYPE_UNSPECIFIED",
		1: "PROTOCOL_TYPE_TCP",
		2: "PROTOCOL_TYPE_HTTP",
		3: "PROTOCOL_TYPE_TLS",
		4: "PROTOCOL_TYPE_DNS",
	}
	ProtocolType_value = map[string]int32{
		"PROTOCOL_TYPE_UNSPECIFIED": 0,
		"PROTOCOL_TYPE_TCP":         1,
		"PROTOCOL_TYPE_HTTP":        2,
		"PROTOCOL_TYPE_TLS":         3,
		"PROTOCOL_TYPE_DNS":         4,
	}
)

func (x ProtocolType) Enum() *ProtocolType {
	p := new(ProtocolType)
	*p = x
	return p
}

func (x ProtocolType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtocolType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_traffic_assessment_proto_enumTypes[0].Descriptor()
}

func (ProtocolType) Type() protoreflect.EnumType {
	return &file_proto_traffic_assessment_proto_enumTypes[0]
}

func (x ProtocolType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProtocolType.Descriptor instead.
func (ProtocolType) EnumDescriptor() ([]byte, []int) {
	return file_proto_traffic_assessment_proto_rawDescGZIP(), []int{0}
}

type Verdict_Action int32

const (
	Verdict_ACTION_ALLOW    Verdict_Action = 0
	Verdict_ACTION_BLOCK    Verdict_Action = 1
	Verdict_ACTION_MITIGATE Verdict_Action = 2 // Modify payload before passing it on
	Verdict_ACTION_OBSERVE  Verdict_Action = 3 // Allow but log more aggressively
	Verdict_ACTION_HOLD     Verdict_Action = 4 // Hold for further analysis
)

// Enum value maps for Verdict_Action.
var (
	Verdict_Action_name = map[int32]string{
		0: "ACTION_ALLOW",
		1: "ACTION_BLOCK",
		2: "ACTION_MITIGATE",
		3: "ACTION_OBSERVE",
		4: "ACTION_HOLD",
	}
	Verdict_Action_value = map[string]int32{
		"ACTION_ALLOW":    0,
		"ACTION_BLOCK":    1,
		"ACTION_MITIGATE": 2,
		"ACTION_OBSERVE":  3,
		"ACTION_HOLD":     4,
	}
)

func (x Verdict_Action) Enum() *Verdict_Action {
	p := new(Verdict_Action)
	*p = x
	return p
}

func (x Verdict_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Verdict_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_traffic_assessment_proto_enumTypes[1].Descriptor()
}

func (Verdict_Action) Type() protoreflect.EnumType {
	return &file_proto_traffic_assessment_proto_enumTypes[1]
}

func (x Verdict_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Verdict_Action.Descriptor instead.
func (Verdict_Action) EnumDescriptor() ([]byte, []int) {
	return file_proto_traffic_assessment_proto_rawDescGZIP(), []int{3, 0}
}

// Metadata about the originating process and network context
type TrafficMetadata struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Pid                uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`                                             // Process ID from eBPF
	Comm               string                 `protobuf:"bytes,2,opt,name=comm,proto3" json:"comm,omitempty"`                                            // Process name (e.g., "python3", "curl")
	FileDescriptor     uint32                 `protobuf:"varint,3,opt,name=file_descriptor,json=fileDescriptor,proto3" json:"file_descriptor,omitempty"` // FD of the socket
	SourceAddress      string                 `protobuf:"bytes,4,opt,name=source_address,json=sourceAddress,proto3" json:"source_address,omitempty"`     // Captured IP
	SourcePort         uint32                 `protobuf:"varint,5,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`             // Captured Port
	DestinationAddress string                 `protobuf:"bytes,6,opt,name=destination_address,json=destinationAddress,proto3" json:"destination_address,omitempty"`
	DestinationPort    uint32                 `protobuf:"varint,7,opt,name=destination_port,json=destinationPort,proto3" json:"destination_port,omitempty"`
	TenantId           string                 `protobuf:"bytes,8,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`  // Multi-tenancy context
	CgroupId           uint64                 `protobuf:"varint,9,opt,name=cgroup_id,json=cgroupId,proto3" json:"cgroup_id,omitempty"` // Container/Pod ID
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TrafficMetadata) Reset() {
	*x = TrafficMetadata{}
	mi := &file_proto_traffic_assessment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficMetadata) ProtoMessage() {}

func (x *TrafficMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_traffic_assessment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficMetadata.ProtoReflect.Descriptor instead.
func (*TrafficMetadata) Descriptor() ([]byte, []int) {
	return file_proto_traffic_assessment_proto_rawDescGZIP(), []int{0}
}

func (x *TrafficMetadata) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *TrafficMetadata) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

func (x *TrafficMetadata) GetFileDescriptor() uint32 {
	if x != nil {
		return x.FileDescriptor
	}
	return 0
}

func (x *TrafficMetadata) GetSourceAddress() string {
	if x != nil {
		return x.SourceAddress
	}
	return ""
}

func (x *TrafficMetadata) GetSourcePort() uint32 {
	if x != nil {
		return x.SourcePort
	}
	return 0
}

func (x *TrafficMetadata) GetDestinationAddress() string {
	if x != nil {
		return x.DestinationAddress
	}
	return ""
}

func (x *TrafficMetadata) GetDestinationPort() uint32 {
	if x != nil {
		return x.DestinationPort
	}
	return 0
}

func (x *TrafficMetadata) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TrafficMetadata) GetCgroupId() uint64 {
	if x != nil {
		return x.CgroupId
	}
	return 0
}

type AssessmentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                 // UUID for tracking through the pipeline
	SequenceNumber uint64                 `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"` // For ordering
	CapturedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=captured_at,json=capturedAt,proto3" json:"captured_at,omitempty"`
	Timeout        *durationpb.Duration   `protobuf:"bytes,4,opt,name=timeout,proto3" json:"timeout,omitempty"` // Max time Jury has to decide
	Metadata       *TrafficMetadata       `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	RawPayload     []byte                 `protobuf:"bytes,6,opt,name=raw_payload,json=rawPayload,proto3" json:"raw_payload,omitempty"` // The intercepted buffer (max 1024 bytes)
	Protocol       ProtocolType           `protobuf:"varint,7,opt,name=protocol,proto3,enum=ocx.v1.ProtocolType" json:"protocol,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AssessmentRequest) Reset() {
	*x = AssessmentRequest{}
	mi := &file_proto_traffic_assessment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssessmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssessmentRequest) ProtoMessage() {}

func (x *AssessmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_traffic_assessment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssessmentRequest.ProtoReflect.Descriptor instead.
func (*AssessmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_traffic_assessment_proto_rawDescGZIP(), []int{1}
}

func (x *AssessmentRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AssessmentRequest) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *AssessmentRequest) GetCapturedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CapturedAt
	}
	return nil
}

func (x *AssessmentRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *AssessmentRequest) GetMetadata() *TrafficMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AssessmentRequest) GetRawPayload() []byte {
	if x != nil {
		return x.RawPayload
	}
	return nil
}

func (x *AssessmentRequest) GetProtocol() ProtocolType {
	if x != nil {
		return x.Protocol
	}
	return ProtocolType_PROTOCOL_TYPE_UNSPECIFIED
}

type AssessmentResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // Must match the AssessmentRequest ID
	Verdict         *Verdict               `protobuf:"bytes,2,opt,name=verdict,proto3" json:"verdict,omitempty"`
	ConfidenceScore float32                `protobuf:"fixed32,3,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`                                    // 0.0 to 1.0
	Reasoning       string                 `protobuf:"bytes,4,opt,name=reasoning,proto3" json:"reasoning,omitempty"`                                                                         // Optional: Why the Jury made this choice
	Metadata        map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Extensible fields (e.g., "new_ttl": "60")
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AssessmentResponse) Reset() {
	*x = AssessmentResponse{}
	mi := &file_proto_traffic_assessment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssessmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssessmentResponse) ProtoMessage() {}

func (x *AssessmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_traffic_assessment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssessmentResponse.ProtoReflect.Descriptor instead.
func (*AssessmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_traffic_assessment_proto_rawDescGZIP(), []int{2}
}

func (x *AssessmentResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AssessmentResponse) GetVerdict() *Verdict {
	if x != nil {
		return x.Verdict
	}
	return nil
}

func (x *AssessmentResponse) GetConfidenceScore() float32 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *AssessmentResponse) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *AssessmentResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Verdict struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        Verdict_Action         `protobuf:"varint,1,opt,name=action,proto3,enum=ocx.v1.Verdict_Action" json:"action,omitempty"`
	TrustLevel    float32                `protobuf:"fixed32,2,opt,name=trust_level,json=trustLevel,proto3" json:"trust_level,omitempty"` // Updated trust level 0.0-1.0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Verdict) Reset() {
	*x = Verdict{}
	mi := &file_proto_traffic_assessment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Verdict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verdict) ProtoMessage() {}

func (x *Verdict) ProtoReflect() protoreflect.Message {
	mi := &file_proto_traffic_assessment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Verdict.ProtoReflect.Descriptor instead.
func (*Verdict) Descriptor() ([]byte, []int) {
	return file_proto_traffic_assessment_proto_rawDescGZIP(), []int{3}
}

func (x *Verdict) GetAction() Verdict_Action {
	if x != nil {
		return x.Action
	}
	return Verdict_ACTION_ALLOW
}

func (x *Verdict) GetTrustLevel() float32 {
	if x != nil {
		return x.TrustLevel
	}
	return 0
}

var File_proto_traffic_assessment_proto protoreflect.FileDescriptor

const file_proto_traffic_assessment_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/traffic_assessment.proto\x12\x06ocx.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xbe\x02\n" +
	"\x0fTrafficMetadata\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12\x12\n" +
	"\x04comm\x18\x02 \x01(\tR\x04comm\x12'\n" +
	"\x0ffile_descriptor\x18\x03 \x01(\rR\x0efileDescriptor\x12%\n" +
	"\x0esource_address\x18\x04 \x01(\tR\rsourceAddress\x12\x1f\n" +
	"\vsource_port\x18\x05 \x01(\rR\n" +
	"sourcePort\x12/\n" +
	"\x13destination_address\x18\x06 \x01(\tR\x12destinationAddress\x12)\n" +
	"\x10destination_port\x18\a \x01(\rR\x0fdestinationPort\x12\x1b\n" +
	"\ttenant_id\x18\b \x01(\tR\btenantId\x12\x1b\n" +
	"\tcgroup_id\x18\t \x01(\x04R\bcgroupId\"\xd5\x02\n" +
	"\x11AssessmentRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x04R\x0esequenceNumber\x12;\n" +
	"\vcaptured_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"capturedAt\x123\n" +
	"\atimeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x123\n" +
	"\bmetadata\x18\x05 \x01(\v2\x17.ocx.v1.TrafficMetadataR\bmetadata\x12\x1f\n" +
	"\vraw_payload\x18\x06 \x01(\fR\n" +
	"rawPayload\x120\n" +
	"\bprotocol\x18\a \x01(\x0e2\x14.ocx.v1.ProtocolTypeR\bprotocol\"\xaa\x02\n" +
	"\x12AssessmentResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12)\n" +
	"\averdict\x18\x02 \x01(\v2\x0f.ocx.v1.VerdictR\averdict\x12)\n" +
	"\x10confidence_score\x18\x03 \x01(\x02R\x0fconfidenceScore\x12\x1c\n" +
	"\treasoning\x18\x04 \x01(\tR\treasoning\x12D\n" +
	"\bmetadata\x18\x05 \x03(\v2(.ocx.v1.AssessmentResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc2\x01\n" +
	"\aVerdict\x12.\n" +
	"\x06action\x18\x01 \x01(\x0e2\x16.ocx.v1.Verdict.ActionR\x06action\x12\x1f\n" +
	"\vtrust_level\x18\x02 \x01(\x02R\n" +
	"trustLevel\"f\n" +
	"\x06Action\x12\x10\n" +
	"\fACTION_ALLOW\x10\x00\x12\x10\n" +
	"\fACTION_BLOCK\x10\x01\x12\x13\n" +
	"\x0fACTION_MITIGATE\x10\x02\x12\x12\n" +
	"\x0eACTION_OBSERVE\x10\x03\x12\x0f\n" +
	"\vACTION_HOLD\x10\x04*\x8a\x01\n" +
	"\fProtocolType\x12\x1d\n" +
	"\x19PROTOCOL_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11PROTOCOL_TYPE_TCP\x10\x01\x12\x16\n" +
	"\x12PROTOCOL_TYPE_HTTP\x10\x02\x12\x15\n" +
	"\x11PROTOCOL_TYPE_TLS\x10\x03\x12\x15\n" +
	"\x11PROTOCOL_TYPE_DNS\x10\x042^\n" +
	"\x0fTrafficAssessor\x12K\n" +
	"\x0eInspectTraffic\x12\x19.ocx.v1.AssessmentRequest\x1a\x1a.ocx.v1.AssessmentResponse(\x010\x01B+Z)github.com/ocx/backend/gen/proto/v1;ocxv1b\x06proto3"

var (
	file_proto_traffic_assessment_proto_rawDescOnce sync.Once
	file_proto_traffic_assessment_proto_rawDescData []byte
)

func file_proto_traffic_assessment_proto_rawDescGZIP() []byte {
	file_proto_traffic_assessment_proto_rawDescOnce.Do(func() {
		file_proto_traffic_assessment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_traffic_assessment_proto_rawDesc), len(file_proto_traffic_assessment_proto_rawDesc)))
	})
	return file_proto_traffic_assessment_proto_rawDescData
}

var file_proto_traffic_assessment_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_traffic_assessment_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_traffic_assessment_proto_goTypes = []any{
	(ProtocolType)(0),             // 0: ocx.v1.ProtocolType
	(Verdict_Action)(0),           // 1: ocx.v1.Verdict.Action
	(*TrafficMetadata)(nil),       // 2: ocx.v1.TrafficMetadata
	(*AssessmentRequest)(nil),     // 3: ocx.v1.AssessmentRequest
	(*AssessmentResponse)(nil),    // 4: ocx.v1.AssessmentResponse
	(*Verdict)(nil),               // 5: ocx.v1.Verdict
	nil,                           // 6: ocx.v1.AssessmentResponse.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 8: google.protobuf.Duration
}
var file_proto_traffic_assessment_proto_depIdxs = []int32{
	7, // 0: ocx.v1.AssessmentRequest.captured_at:type_name -> google.protobuf.Timestamp
	8, // 1: ocx.v1.AssessmentRequest.timeout:type_name -> google.protobuf.Duration
	2, // 2: ocx.v1.AssessmentRequest.metadata:type_name -> ocx.v1.TrafficMetadata
	0, // 3: ocx.v1.AssessmentRequest.protocol:type_name -> ocx.v1.ProtocolType
	5, // 4: ocx.v1.AssessmentResponse.verdict:type_name -> ocx.v1.Verdict
	6, // 5: ocx.v1.AssessmentResponse.metadata:type_name -> ocx.v1.AssessmentResponse.MetadataEntry
	1, // 6: ocx.v1.Verdict.action:type_name -> ocx.v1.Verdict.Action
	3, // 7: ocx.v1.TrafficAssessor.InspectTraffic:input_type -> ocx.v1.AssessmentRequest
	4, // 8: ocx.v1.TrafficAssessor.InspectTraffic:output_type -> ocx.v1.AssessmentResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_traffic_assessment_proto_init() }
func file_proto_traffic_assessment_proto_init() {
	if File_proto_traffic_assessment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_traffic_assessment_proto_rawDesc), len(file_proto_traffic_assessment_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_traffic_assessment_proto_goTypes,
		DependencyIndexes: file_proto_traffic_assessment_proto_depIdxs,
		EnumInfos:         file_proto_traffic_assessment_proto_enumTypes,
		MessageInfos:      file_proto_traffic_assessment_proto_msgTypes,
	}.Build()
	File_proto_traffic_assessment_proto = out.File
	file_proto_traffic_assessment_proto_goTypes = nil
	file_proto_traffic_assessment_proto_depIdxs = nil
}
