// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: pb/ocx_handshake.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InterOCXHandshakeService_InitiateHandshake_FullMethodName   = "/federation.InterOCXHandshakeService/InitiateHandshake"
	InterOCXHandshakeService_RespondToChallenge_FullMethodName  = "/federation.InterOCXHandshakeService/RespondToChallenge"
	InterOCXHandshakeService_ExchangeAttestation_FullMethodName = "/federation.InterOCXHandshakeService/ExchangeAttestation"
	InterOCXHandshakeService_PerformHandshake_FullMethodName    = "/federation.InterOCXHandshakeService/PerformHandshake"
	InterOCXHandshakeService_GetHandshakeStatus_FullMethodName  = "/federation.InterOCXHandshakeService/GetHandshakeStatus"
)

// InterOCXHandshakeServiceClient is the client API for InterOCXHandshakeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InterOCXHandshakeServiceClient interface {
	// Initiate a new handshake (Step 1: HELLO)
	InitiateHandshake(ctx context.Context, in *HandshakeHello, opts ...grpc.CallOption) (*HandshakeChallenge, error)
	// Respond to challenge (Step 3: PROOF)
	RespondToChallenge(ctx context.Context, in *HandshakeProof, opts ...grpc.CallOption) (*HandshakeVerify, error)
	// Exchange attestation (Step 5: ATTESTATION)
	ExchangeAttestation(ctx context.Context, in *HandshakeAttestation, opts ...grpc.CallOption) (*HandshakeResult, error)
	// Full bidirectional streaming handshake (all 6 steps)
	PerformHandshake(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HandshakeMessage, HandshakeMessage], error)
	// Get handshake status
	GetHandshakeStatus(ctx context.Context, in *HandshakeStatusRequest, opts ...grpc.CallOption) (*HandshakeState, error)
}

type interOCXHandshakeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInterOCXHandshakeServiceClient(cc grpc.ClientConnInterface) InterOCXHandshakeServiceClient {
	return &interOCXHandshakeServiceClient{cc}
}

func (c *interOCXHandshakeServiceClient) InitiateHandshake(ctx context.Context, in *HandshakeHello, opts ...grpc.CallOption) (*HandshakeChallenge, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeChallenge)
	err := c.cc.Invoke(ctx, InterOCXHandshakeService_InitiateHandshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interOCXHandshakeServiceClient) RespondToChallenge(ctx context.Context, in *HandshakeProof, opts ...grpc.CallOption) (*HandshakeVerify, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeVerify)
	err := c.cc.Invoke(ctx, InterOCXHandshakeService_RespondToChallenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interOCXHandshakeServiceClient) ExchangeAttestation(ctx context.Context, in *HandshakeAttestation, opts ...grpc.CallOption) (*HandshakeResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeResult)
	err := c.cc.Invoke(ctx, InterOCXHandshakeService_ExchangeAttestation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interOCXHandshakeServiceClient) PerformHandshake(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HandshakeMessage, HandshakeMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InterOCXHandshakeService_ServiceDesc.Streams[0], InterOCXHandshakeService_PerformHandshake_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HandshakeMessage, HandshakeMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InterOCXHandshakeService_PerformHandshakeClient = grpc.BidiStreamingClient[HandshakeMessage, HandshakeMessage]

func (c *interOCXHandshakeServiceClient) GetHandshakeStatus(ctx context.Context, in *HandshakeStatusRequest, opts ...grpc.CallOption) (*HandshakeState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeState)
	err := c.cc.Invoke(ctx, InterOCXHandshakeService_GetHandshakeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InterOCXHandshakeServiceServer is the server API for InterOCXHandshakeService service.
// All implementations must embed UnimplementedInterOCXHandshakeServiceServer
// for forward compatibility.
type InterOCXHandshakeServiceServer interface {
	// Initiate a new handshake (Step 1: HELLO)
	InitiateHandshake(context.Context, *HandshakeHello) (*HandshakeChallenge, error)
	// Respond to challenge (Step 3: PROOF)
	RespondToChallenge(context.Context, *HandshakeProof) (*HandshakeVerify, error)
	// Exchange attestation (Step 5: ATTESTATION)
	ExchangeAttestation(context.Context, *HandshakeAttestation) (*HandshakeResult, error)
	// Full bidirectional streaming handshake (all 6 steps)
	PerformHandshake(grpc.BidiStreamingServer[HandshakeMessage, HandshakeMessage]) error
	// Get handshake status
	GetHandshakeStatus(context.Context, *HandshakeStatusRequest) (*HandshakeState, error)
	mustEmbedUnimplementedInterOCXHandshakeServiceServer()
}

// UnimplementedInterOCXHandshakeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInterOCXHandshakeServiceServer struct{}

func (UnimplementedInterOCXHandshakeServiceServer) InitiateHandshake(context.Context, *HandshakeHello) (*HandshakeChallenge, error) {
	return nil, status.Error(codes.Unimplemented, "method InitiateHandshake not implemented")
}
func (UnimplementedInterOCXHandshakeServiceServer) RespondToChallenge(context.Context, *HandshakeProof) (*HandshakeVerify, error) {
	return nil, status.Error(codes.Unimplemented, "method RespondToChallenge not implemented")
}
func (UnimplementedInterOCXHandshakeServiceServer) ExchangeAttestation(context.Context, *HandshakeAttestation) (*HandshakeResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ExchangeAttestation not implemented")
}
func (UnimplementedInterOCXHandshakeServiceServer) PerformHandshake(grpc.BidiStreamingServer[HandshakeMessage, HandshakeMessage]) error {
	return status.Error(codes.Unimplemented, "method PerformHandshake not implemented")
}
func (UnimplementedInterOCXHandshakeServiceServer) GetHandshakeStatus(context.Context, *HandshakeStatusRequest) (*HandshakeState, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHandshakeStatus not implemented")
}
func (UnimplementedInterOCXHandshakeServiceServer) mustEmbedUnimplementedInterOCXHandshakeServiceServer() {
}
func (UnimplementedInterOCXHandshakeServiceServer) testEmbeddedByValue() {}

// UnsafeInterOCXHandshakeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InterOCXHandshakeServiceServer will
// result in compilation errors.
type UnsafeInterOCXHandshakeServiceServer interface {
	mustEmbedUnimplementedInterOCXHandshakeServiceServer()
}

func RegisterInterOCXHandshakeServiceServer(s grpc.ServiceRegistrar, srv InterOCXHandshakeServiceServer) {
	// If the following call panics, it indicates UnimplementedInterOCXHandshakeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InterOCXHandshakeService_ServiceDesc, srv)
}

func _InterOCXHandshakeService_InitiateHandshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeHello)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterOCXHandshakeServiceServer).InitiateHandshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterOCXHandshakeService_InitiateHandshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterOCXHandshakeServiceServer).InitiateHandshake(ctx, req.(*HandshakeHello))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterOCXHandshakeService_RespondToChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeProof)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterOCXHandshakeServiceServer).RespondToChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterOCXHandshakeService_RespondToChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterOCXHandshakeServiceServer).RespondToChallenge(ctx, req.(*HandshakeProof))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterOCXHandshakeService_ExchangeAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeAttestation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterOCXHandshakeServiceServer).ExchangeAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterOCXHandshakeService_ExchangeAttestation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterOCXHandshakeServiceServer).ExchangeAttestation(ctx, req.(*HandshakeAttestation))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterOCXHandshakeService_PerformHandshake_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(InterOCXHandshakeServiceServer).PerformHandshake(&grpc.GenericServerStream[HandshakeMessage, HandshakeMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InterOCXHandshakeService_PerformHandshakeServer = grpc.BidiStreamingServer[HandshakeMessage, HandshakeMessage]

func _InterOCXHandshakeService_GetHandshakeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterOCXHandshakeServiceServer).GetHandshakeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterOCXHandshakeService_GetHandshakeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterOCXHandshakeServiceServer).GetHandshakeStatus(ctx, req.(*HandshakeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InterOCXHandshakeService_ServiceDesc is the grpc.ServiceDesc for InterOCXHandshakeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InterOCXHandshakeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "federation.InterOCXHandshakeService",
	HandlerType: (*InterOCXHandshakeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitiateHandshake",
			Handler:    _InterOCXHandshakeService_InitiateHandshake_Handler,
		},
		{
			MethodName: "RespondToChallenge",
			Handler:    _InterOCXHandshakeService_RespondToChallenge_Handler,
		},
		{
			MethodName: "ExchangeAttestation",
			Handler:    _InterOCXHandshakeService_ExchangeAttestation_Handler,
		},
		{
			MethodName: "GetHandshakeStatus",
			Handler:    _InterOCXHandshakeService_GetHandshakeStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PerformHandshake",
			Handler:       _InterOCXHandshakeService_PerformHandshake_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pb/ocx_handshake.proto",
}
